language: java
jdk:
 - oraclejdk8

script:
   mvn test -Ptest

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: private-lessons-api

notifications:
  email:
    - oprysk.nazar@gmail.com